### ISSUE TITLE
Error while starting Notebook or REPL

### ISSUE THREAD

**Issue by rafpyprog** [jupyterlite/jupyterlite#656] opened 2022-05-31 21:27 UTC
A running Jupyterlite site started throwing the following error on console. There were no changes on the application. Apparently the exception comes from the traitlets package.

## Description
![image](https://user-images.githubusercontent.com/17583740/171286609-55c29a03-912c-4a95-9991-9ba911465592.png)

## Reproduce

Start REPL or a Jupyter Notebook

## Expected behavior

Kernel starts without error.

## Context

- JupyterLite version: 0.1.0b4
- Operating System and version: Linux
- Browser and version: Firefox 78.9

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jtpio** [comment] 2022-06-01 06:36
Thanks @rafpyprog for reporting.

A new release of `traitlets` was published a couple of hours ago, which might be related: https://github.com/ipython/traitlets/releases/tag/5.2.2

**Comment by jtpio** [comment] 2022-06-01 06:42
There appears to be a similar issue on the JupyterLab repo: https://github.com/jupyterlab/jupyterlab/issues/12631

**Comment by jtpio** [comment] 2022-12-21 18:59
Closing as fixed since this does not seem to be reproducible anymore.

Feel free to open a new issue if you notice any error, thanks!

**Closed by jtpio** 2022-12-21 18:59 UTC
Labels: bug
