### ISSUE TITLE
Interpreting content between two `$`s when it shouldn't

### ISSUE THREAD

**Issue by konstell** [jupyterlite/jupyterlite#305] opened 2021-08-16 06:52 UTC
## Description
Inside code fences in a Markdown cell, JupyterLite is interpreting things between two dollar signs as MathJax. This is presumably unintended.

## Reproduce
In a Markdown cell, put in
``````
```python
$ python3.9 -i code.py
>>> test1()
{'z': 'Q', 'foo': 2}
>>> test2()
>>>
$ python3.9 -i code.py
>>> test2()
forty-two
spam
>>> 
```
``````

The text rendered is 
```
@@0@@ python3.9 -i code.py
>>> test2()
forty-two
spam
>>> 
```

The content between the two dollar signs is rendered as `@@0@@`. However, if I add a newline anywhere between the two dollar signs, the code would render as-is.

## Expected behavior

I expected the code inside the code fences to be rendered as-is and not interpreted as MathJax.

## Context

- JupyterLite version: 0.1.0a6
- Operating System and version: Ubuntu 20.04.2
- Browser and version: Brave Browser, Version 1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit)

<details><summary>Browser Output</summary>
<pre><code class="cm-s-jupyter language-python"><span class="cm-operator">@</span><span class="cm-operator">@</span><span class="cm-number">0</span><span class="cm-operator">@</span><span class="cm-operator">@</span> <span class="cm-variable">python3</span><span class="cm-number">.9</span> <span class="cm-operator">-</span><span class="cm-variable">i</span> <span class="cm-variable">code</span>.<span class="cm-property">py</span>
<span class="cm-operator">&gt;&gt;&gt;</span> <span class="cm-variable">test2</span>()
<span class="cm-variable">forty</span><span class="cm-operator">-</span><span class="cm-variable">two</span>
<span class="cm-variable">spam</span>
<span class="cm-operator">&gt;&gt;&gt;</span> 
</code></pre>
</details>

**Comment by gilch** [comment] 2021-08-16 07:04
Could be an upstream issue. I tried the example and I noticed this also happens in JupyterLab (I was on `jupyterlab==3.0.0rc15` at the time. I'll try upgrading.) It does not seem to happen in the old Jupyter notebooks though.

**Comment by gilch** [comment] 2021-08-16 07:23
Reproduced in JupyterLab Version 3.1.6, when started with `jupyter-lab`. I see the `@@0@@`.

When I start it with `jupyter-notebook` it says the server is version 6.4.3, and the example renders properly.

When running JupyterLite, it doesn't matter if I reach the notebook using the `retro` or the `lab` URL. They both render it as `@@0@@`.

**Comment by gilch** [comment] 2021-08-16 07:52
Separate fences don't help.

    ```bash
    $ python3.9 -i code.py
    ```
    ```python
    >>> test1()
    {'z': 'Q', 'foo': 2}
    >>> test2()
    >>>
    ```
    ```bash
    $ python3.9 -i code.py
    ```
    ```python
    >>> test2()
    forty-two
    spam
    >>> 
    ```
renders like

    $ python3.9 -i code.py
    ```
    ```python
    >>> test1()
    {'z': 'Q', 'foo': 2}
    >>> test2()
    >>>
    ```
    ```bash
    $ python3.9 -i code.py
    
    >>> test2()
    forty-two
    spam
    >>>

**Comment by bollwyvl** [comment] 2021-08-17 01:29
Yep, MathJax presents an on-going struggle. Definitely raise the issue upstream on JupyterLab!

**Comment by krassowski** [comment] 2021-11-19 01:21
Hey! This is getting fixed in https://github.com/jupyterlab/jupyterlab/pull/11479. Please feel welcome to try it out on binder and let me know of any edge cases.

**Comment by jtpio** [comment] 2021-11-19 13:04
Nice, thanks @krassowski for the heads up!

**Comment by bollwyvl** [comment] 2022-03-12 17:12
Seems to be fixed:

![Screenshot from 2022-03-12 11-12-17](https://user-images.githubusercontent.com/45380/158027780-b0c99476-da53-437d-a323-8343aa86ac35.png)


 please reopen if it persists

**Closed by bollwyvl** 2022-03-12 17:12 UTC
Labels: bug, upstream
