### ISSUE TITLE
"Open from URL" with the path url query parameter

### ISSUE THREAD

**Issue by dgcdevelopment** [jupyterlite/jupyterlite#774] opened 2022-08-18 13:33 UTC
### Problem
Being able to open a notebook from a external source as a query parameter

### Proposed Solution

path query paramater used in the same way as open from url already implemented

**Comment by bollwyvl** [comment] 2022-08-22 01:48
Duplicate of #430.

**Closed by bollwyvl** 2022-08-22 01:48 UTC
Labels: duplicate, enhancement, extension idea
