### ISSUE TITLE
Does not work if you start classic first

### ISSUE THREAD

**Issue by krassowski** [jupyterlite/jupyterlite#79] opened 2021-04-28 16:48 UTC
## Description

Noted when experimenting during today's JupyterLab call.

## Reproduce

In private window:

1. Open https://jupyterlite.readthedocs.io/en/latest/try/classic
2. See the page loads ok
3. Click on "New notebook"
4. **See the notebook never loads**
5. See JupyterLab does not start from https://jupyterlite.readthedocs.io/en/latest/try/lab
6. See that clicking on Untitled.ipynb from classic listing opens a blank page; see the only message in console is "Starting app"

Close private window, open a new private window:

1. Open https://jupyterlite.readthedocs.io/en/latest/try/lab
2. Create a new "Pyolite" notebook from Launcher
3. See the notebook launches and works smoothly
4. Open https://jupyterlite.readthedocs.io/en/latest/try/classic
5. Open Untitled.ipynb and see that it works now
6. Click on "New notebook"
7. **See that the notebook is created and works well**

Some very uneducated guesses:
- maybe the notebook created from classic interface is missing kernel type and this causes the issue
- maybe some things that are saved in the browser local storage do not get correctly saved if we start with opening classic rather than lab?
- or maybe there is a plugin missing in the classic that is required?

## Context

- Browser and version:
  - Google Chrome 90.0.4430.72
  - Microsoft Edge 91.0.864.1

**Comment by krassowski** [comment] 2021-04-28 18:42
Btw, I am impressed with the startup times. If we could use that for frontend development of extensions it would save so much time!

**Comment by jtpio** [comment] 2021-04-29 08:18
Thanks @krassowski!

I could indeed reproduce it in Chromium 90 in a private window, but not in Firefox.

It could indeed be related to not being able to access `localStorage` in a private window, but still waiting for it to be ready somewhere in the code. We use `localForage` which chooses `localStorage` or `indexedDB` depending on availability.

**Comment by jtpio** [comment] 2021-04-29 08:18
> If we could use that for frontend development of extensions it would save so much time!

That might be possible once there is support for federated extensions (#55 and #58)

**Comment by jtpio** [comment] 2021-08-28 12:41
@krassowski would you mind trying again with the latest from `main`? 

Looks like this issue might be fixed now.

**Comment by jtpio** [comment] 2021-09-01 06:11
After playing around with the retro interface, I was unable to reproduce the issue.

Closing, but feel free to reopen or open a new issue if needed. Thanks!

**Closed by jtpio** 2021-09-01 06:11 UTC
