### ISSUE TITLE
lzma Module

### ISSUE THREAD

**Issue by ErmiasB3** [jupyterlite/jupyterlite#544] opened 2022-03-10 02:53 UTC
importing pandas is not working bringing up the below error:

`/lib/python3.9/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)`

**Comment by bollwyvl** [comment] 2022-03-10 03:09
This is a known, yet mostly harmless, upstream issue:
https://github.com/pyodide/pyodide/issues/877#issuecomment-763010175

**Comment by bollwyvl** [comment] 2022-03-12 16:59
Actually, closing as dupe of https://github.com/jupyterlite/jupyterlite/issues/273

**Closed by bollwyvl** 2022-03-12 16:59 UTC
