### ISSUE TITLE
ENH: Pluggable Cloud Storage provider API; git, jupyter/rtc

### ISSUE THREAD

**Issue by westurner** [jupyterlite/jupyterlite#464] opened 2022-02-01 22:43 UTC
### Problem

JupyterLite users need a way to save their notebooks to their [Cloud Storage provider [drive,]], because otherwise their locally-saved notebooks are lost upon {browser cache reset is it?,}?

### Proposed Solution

* [ ] ENH: Build or integrate a Cloud Storage provider abstraction that enables one or more implementations to enable users to save their notebooks and other files to cloud storage?
  * [ ] https://github.com/jupyterlite/jupyterlite/issues/465
    * [ ] https://github.com/jupyterlab/jupyterlab-google-drive/issues/203
* [ ] DOC: when is data saved locally in a browser cache instance lost in JupyterLite?
* [ ] DOC,BUG,REF: how does Cloud Storage interact with browser-tab-local git with e.g. https://github.com/jupyterlab/jupyterlab-git ?

### Additional context

- https://github.com/jupyterlite/jupyterlite/issues/430
- https://github.com/jupyterlite/jupyterlite/issues/403
- https://github.com/jupyterlite/jupyterlite/issues/318
- https://github.com/jupyterlab/jupyterlab-git
- https://github.com/jupyterlab/rtc

**Comment by bollwyvl** [comment] 2022-02-02 14:22
duplicate of #315

**Closed by bollwyvl** 2022-02-02 14:22 UTC
Labels: enhancement
