### ISSUE TITLE
Cannot open `gzip` file larger than ~1MB (`ReadError: not a gzip file`)

### ISSUE THREAD

**Issue by michaelweinold** [jupyterlite/jupyterlite#1153] opened 2023-09-17 12:47 UTC
## Description

It seems that it is currently impossible to open gzip/tarball files of size >1MB. Tested using both the `xeus-python-kernel` and the `pyodide` based Kernel.

## Reproduce

To test, generate a few gzipped tarfiles that increase in size:

```python
import os
import tarfile
import gzip
import shutil

def generate_files():
    # Create a directory to store the files
    if not os.path.exists('files'):
        os.makedirs('files')
    
    # Generate 10 files, each 0.2MB larger than the previous one
    file_size = 100000  # 0.1MB
    for i in range(10):
        file_name = f'files/file_{i}.txt'
        with open(file_name, 'wb') as f:
            f.write(os.urandom(file_size))
        file_size += 200000  # 0.2MB larger than previous file
    
    # Create the gzipped tarball files
    for i in range(10):
        tarball_name = f'files_{i+1}.tar'
        with tarfile.open(tarball_name, 'w') as tar:
            for j in range(i+1):
                file_name = f'files/file_{j}.txt'
                tar.add(file_name)
        with open(tarball_name, 'rb') as f_in:
            with gzip.open(tarball_name + '.gz', 'wb') as f_out:
                shutil.copyfileobj(f_in, f_out)
        os.remove(tarball_name)
```

This returns:

```
file_1.tar.gz: 100KB
file_2.tar.gz: 401KB
file_3.tar.gz: 901KB
file_4.tar.gz: 1.6MB
...
```

Attempting to open the `*.tar.gz` files works only for those files ~<1MB. For `file_4.tar.gz`, the command:

```python
import tarfile
tarfile.open(name='files_1.tar.gz',mode='r:gz')
```

returns:

```
---------------------------------------------------------------------------
BadGzipFile                               Traceback (most recent call last)
File /lib/python3.10/tarfile.py:1686, in TarFile.gzopen(cls, name, mode, fileobj, compresslevel, **kwargs)
   1685 try:
-> 1686     t = cls.taropen(name, mode, fileobj, **kwargs)
   1687 except OSError as e:

File /lib/python3.10/tarfile.py:1663, in TarFile.taropen(cls, name, mode, fileobj, **kwargs)
   1662     raise ValueError("mode must be 'r', 'a', 'w' or 'x'")
-> 1663 return cls(name, mode, fileobj, **kwargs)

File /lib/python3.10/tarfile.py:1523, in TarFile.__init__(self, name, mode, fileobj, format, tarinfo, dereference, ignore_zeros, encoding, errors, pax_headers, debug, errorlevel, copybufsize)
   1522     self.firstmember = None
-> 1523     self.firstmember = self.next()
   1525 if self.mode == "a":
   1526     # Move to the end of the archive,
   1527     # before the first empty block.

File /lib/python3.10/tarfile.py:2358, in TarFile.next(self)
   2357     else:
-> 2358         raise e
   2359 except ImportError:

File /lib/python3.10/tarfile.py:2331, in TarFile.next(self)
   2330 try:
-> 2331     tarinfo = self.tarinfo.fromtarfile(self)
   2332 except EOFHeaderError as e:

File /lib/python3.10/tarfile.py:1113, in TarInfo.fromtarfile(cls, tarfile)
   1110 """Return the next TarInfo object from TarFile object
   1111    tarfile.
   1112 """
-> 1113 buf = tarfile.fileobj.read(BLOCKSIZE)
   1114 obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)

File /lib/python3.10/gzip.py:301, in GzipFile.read(self, size)
    300     raise OSError(errno.EBADF, "read() on write-only GzipFile object")
--> 301 return self._buffer.read(size)

File /lib/python3.10/_compression.py:68, in DecompressReader.readinto(self, b)
     67 with memoryview(b) as view, view.cast("B") as byte_view:
---> 68     data = self.read(len(byte_view))
     69     byte_view[:len(data)] = data

File /lib/python3.10/gzip.py:488, in _GzipReader.read(self, size)
    487 self._init_read()
--> 488 if not self._read_gzip_header():
    489     self._size = self._pos

File /lib/python3.10/gzip.py:436, in _GzipReader._read_gzip_header(self)
    435 if magic != b'\037\213':
--> 436     raise BadGzipFile('Not a gzipped file (%r)' % magic)
    438 (method, flag,
    439  self._last_mtime) = struct.unpack("<BBIxx", self._read_exact(8))

BadGzipFile: Not a gzipped file (b'@Y')

The above exception was the direct cause of the following exception:

ReadError                                 Traceback (most recent call last)
Cell In[6], line 1
----> 1 tarfile.open(name='files_4.tar.gz',mode='r:gz')

File /lib/python3.10/tarfile.py:1633, in TarFile.open(cls, name, mode, fileobj, bufsize, **kwargs)
   1631     else:
   1632         raise CompressionError("unknown compression type %r" % comptype)
-> 1633     return func(name, filemode, fileobj, **kwargs)
   1635 elif "|" in mode:
   1636     filemode, comptype = mode.split("|", 1)

File /lib/python3.10/tarfile.py:1690, in TarFile.gzopen(cls, name, mode, fileobj, compresslevel, **kwargs)
   1688     fileobj.close()
   1689     if mode == 'r':
-> 1690         raise ReadError("not a gzip file") from e
   1691     raise
   1692 except:

ReadError: not a gzip file
```

## Expected behavior

Not that...

## Context

- JupyterLite version: Version 0.1.2
- Operating System and version: N/A
- Browser and version: Safari Version 16.6 (18615.3.12.11.2) and Google Chrome Version 117.0.5938.62 (Official Build) (arm64)

<details><summary>Browser Output</summary>
<pre>
```
[Info] Registering new JupyterLite ServiceWorker – "https://live.brightway.dev/service-worker-f7de73d.js" (1245.cbc7a54.js, line 1)
[Info] JupyterLite ServiceWorker was sucessfully registered (1245.cbc7a54.js, line 1)
[Info] Kernel filesystem and JupyterLite contents will be synced (4931.c1705a1.js, line 1)
[Info] Pyodide contents will be synced with Jupyter Contents (652.5ce30c47c04bb4e7300d.js, line 1)
[Debug] Starting WebSocket: wss://live.brightway.dev/api/kernels/837f8b68-e9e2-4884-8b64-59fb6b4cbe5d (6591.94ed352.js, line 1)
[Debug] Starting WebSocket: wss://live.brightway.dev/api/kernels/837f8b68-e9e2-4884-8b64-59fb6b4cbe5d (6591.94ed352.js, line 1)
[Debug] Starting WebSocket: wss://live.brightway.dev/api/kernels/837f8b68-e9e2-4884-8b64-59fb6b4cbe5d (6591.94ed352.js, line 1)
[Debug] SyntaxError: The string did not match the expected pattern. (6591.94ed352.js, line 1)
[Log] Loading micropip, packaging (pyodide.asm.js, line 9)
[Log] Loaded packaging, micropip (pyodide.asm.js, line 9)
[Log] Loading sqlite3 (pyodide.asm.js, line 9)
[Log] Loaded sqlite3 (pyodide.asm.js, line 9)
[Log] Loading decorator, jedi, parso, pygments, six (pyodide.asm.js, line 9)
[Log] Loaded decorator, six, parso, jedi, pygments (pyodide.asm.js, line 9)
[Debug] SyntaxError: The string did not match the expected pattern. — serverconnection.ts:162 (6591.94ed352.js, line 1)
[Debug] SyntaxError: The string did not match the expected pattern. — serverconnection.ts:162 (6591.94ed352.js, line 1)
[Debug] SyntaxError: The string did not match the expected pattern. — serverconnection.ts:162 (6591.94ed352.js, line 1)
[Debug] Kernel: restarting (837f8b68-e9e2-4884-8b64-59fb6b4cbe5d) (6591.94ed352.js, line 1)
[Info] Pyodide contents will be synced with Jupyter Contents (652.5ce30c47c04bb4e7300d.js, line 1)
[Debug] Starting WebSocket: wss://live.brightway.dev/api/kernels/837f8b68-e9e2-4884-8b64-59fb6b4cbe5d (6591.94ed352.js, line 1)
[Log] Loading micropip, packaging (pyodide.asm.js, line 9)
[Log] Loaded packaging, micropip (pyodide.asm.js, line 9)
[Log] Loading sqlite3 (pyodide.asm.js, line 9)
[Log] Loaded sqlite3 (pyodide.asm.js, line 9)
[Log] Loading jedi, parso, decorator, pygments, six (pyodide.asm.js, line 9)
[Log] Loaded parso, jedi, decorator, pygments, six (pyodide.asm.js, line 9)
[Debug] SyntaxError: The string did not match the expected pattern. — serverconnection.ts:162 (6591.94ed352.js, line 1)
```
</pre>
</details>

**Comment by jtpio** [comment] 2023-09-18 05:52
Thanks @michaelweinold for reporting.

https://github.com/jupyterlite/jupyterlite/pull/1024 added support for chunked uploads, but maybe it does not support gzip files: https://github.com/jupyterlite/jupyterlite/issues/534 (would need to investigate)

**Comment by michaelweinold** [comment] 2023-09-18 14:39
Just to be clear: _Uploading_ (ie. using this magic button):

<img width="84" alt="Screenshot 2023-09-18 at 16 37 54" src="https://github.com/jupyterlite/jupyterlite/assets/23102087/80f51407-36ce-4ba9-9c0f-c2c5728ad1f9">

works just fine (for any file size).

Reading the gzipped files (for instance, once they have been created with [the test function](https://github.com/jupyterlite/jupyterlite/issues/1153#issue-1899772800)) does not work.

**Comment by michaelweinold** [comment] 2023-09-18 15:07
In both cases. I included the test function to show that the issue wasn’t my with my specific files.

**Comment by jtpio** [comment] 2023-11-14 17:04
It could be yes, would need to investigate a bit further to confirm.

**Comment by michaelweinold** [comment] 2024-05-20 15:38
The issue persists on ([complete requirements file](https://github.com/brightway-lca/brightway-live/blob/pyodide/requirements.txt)):

```
jupyterlite-core==0.3.0
jupyterlite-pyodide-kernel==0.3.1
```

The only difference is that now I can not correctly create the successively larger tar-files. The files all remain at a size of a few hundred Bytes. The console tells me:

<img width="500" alt="Screenshot 2024-05-20 at 11 37 11" src="https://github.com/jupyterlite/jupyterlite/assets/23102087/9e64e930-efae-4e5f-92cf-c6ce23c855d8">

```
worker.js:4 setattr size of 0 on FSNode not yet implemented
```

It would be fantastic if we could work with zipped files - any change you could have a look, @jtpio?

**Comment by jtpio** [comment] 2024-05-30 07:21
Thanks @michaelweinold for checking.

I haven't investigated it yet, but will hopefully have a look soon.

**Comment by michaelweinold** [comment] 2024-07-30 07:26
I checked with the latest version of JupyterLite (0.4.0). Unfortunately, the issue persists:

```python
ReadError: not a gzip file
```

**Comment by jtpio** [comment] 2024-07-30 08:56
It's probably still related to the custom contents manager used in JupyterLite, which hasn't changed much for the past release. So still something to be investigated and to be released as a bug fix.

**Comment by katotetsuro** [comment] 2024-10-11 03:46
Hello, @jtpio 

I encountered this issue when I wanted to upload a large numpy .npy file, so I made the following changes:

- Support for chunk loading
- Since each chunk is Base64 encoded, I ensured proper concatenation by taking padding into account

https://github.com/katotetsuro/jupyterlite/commit/8a1c64486a7c4a3a2c08654c86481898c9bb2543

In my local env, I confirmed that an 8MB .npy file uploaded by dragging it into the browser is correctly loaded by the pyodide kernel.

If these changes look good, I can create a PR. What do you think?

**Comment by jtpio** [comment] 2024-10-11 15:04
> If these changes look good, I can create a PR. What do you think?

Yes please do, that would be greatly appreciated! We can then check if all CI checks pass. Thanks!

**Closed** 2024-10-15 07:37 UTC
Labels: bug
