### ISSUE TITLE
Unable to read the dataset(.csv) file in jupyterlite.

### ISSUE THREAD

**Issue by pratik-3110** [jupyterlite/jupyterlite#539] opened 2022-03-07 10:21 UTC
It is not able to read the dataset file uploaded.
When uploaded the file previously in jupyterlab, it worked fine.
Now, the error comes up as-

"FileNotFoundError: [Errno 44] No such file or directory: 'data.csv'". 
Is there another way to read a file?

**Comment by bollwyvl** [comment] 2022-03-07 14:36
Here's a discussion of this topic: https://github.com/jupyterlite/jupyterlite/discussions/91 with a hack at the bottom for getting contents out of indexeddb. 

> previously in jupyterlab

jupyterlite is a substantially different beast than "real" lab, and there are limitations, some of which we don't even know yet.
 
We intend, at some point, on #315 to implement a way to either:
- make all the browser "contents" available inside the kernel
- mount the kernel's filesystem as another file explorer (much like [jupyterlab-github](https://github.com/jupyterlab/jupyterlab-github/)) that would also allow for drag-and-drop upload

However we do this might be colored by making it work well with cross-domain iframe kernels #463 and large files, which would make some of the fun stuff automatically not quite as easy.

**Comment by psychemedia** [comment] 2022-03-08 21:59
I've been trying to capture trick and workarounds here: https://github.com/innovationOUtside/ouseful_jupyterlite_utils

**Comment by bollwyvl** [comment] 2022-03-12 17:00
Closing as dupe of https://github.com/jupyterlite/jupyterlite/issues/119

**Closed by bollwyvl** 2022-03-12 17:00 UTC
Labels: bug
