### ISSUE TITLE
AttributeError: module 'pexpect' has no attribute 'TIMEOUT' while installing in Juypter notebook

### ISSUE THREAD

**Issue by Karan-raj-dev** [jupyterlite/jupyterlite#725] opened 2022-07-09 07:51 UTC
## Couldn't install any of the python libraries

I tried to install the seaborn module for python, but the IDE raised an error - AttributeError: module 'pexpect' has no attribute 'TIMEOUT'

Whenever I use pip this error is raised.

Attached image for your reference.
![image](https://user-images.githubusercontent.com/69041067/178096959-7626a5e7-292e-4cd0-826b-345af795c418.png)

## Reproduce

To reproduce this error, try installing a python seaborn module, or any module.

## Expected behavior

Want to install and use the python module's attributes and methods.

## Context

- JupyterLite version: NA
- Operating System and version: Windows 10
- Browser and version: Microsoft Edge

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by oscar6echo** [comment] 2022-07-09 08:23
Not a bug, but a characteristic.  
There are some differences with regular "desktop" Jupyterlab.  

1/
You need `piplite.install()` those libs which are not in pyodide: [list of packages](https://pyodide.org/en/stable/usage/packages-in-pyodide.html).  
Some will work, like seaborn, some not, like polars, depending on how they are implemented.

2/
A browser being a natural `async` env, some operations need be prefixed by an `await` keyword, some operations need be put in different cells.

3/
When collecting data, usual package `requests` does not work.  
Instead use [pyfetch](https://pyodide.org/en/stable/usage/faq.html). Example:
```py
from pyodide.http import pyfetch

async def download(url, filename):
    response = await pyfetch(url)
    if response.status == 200:
        with open(filename, "wb") as f:
            f.write(await response.bytes())
```

4/
HTTP/S requests maybe stopped by the browser's CORS limitations.  
Example: In the case of seaborn `penguins = sns.load_dataset("penguins")` will be blocked.   
So download separately and upload in Jupyterlite


Total, in your case do:

```py
# in https://jupyterlite.readthedocs.io/en/latest/_static/lab/

# cell
import piplite
await piplite.install('seaborn')

# cell
from pathlib import Path
import pandas as pd
import seaborn as sns

sns.set_theme()
%matplotlib inline

# cell
path = Path('/drive/test-seaborn/penguins.csv')
df = pd.read_csv(path)
df.info()

# cell
sns.histplot(data=df, x="flipper_length_mm", hue="species", multiple="stack");
```

Result:


![Screenshot from 2022-07-09 10-20-35](https://user-images.githubusercontent.com/2219383/178097862-092a8ec9-7475-4e9c-9b49-759804d459a9.png)

**Comment by oscar6echo** [comment] 2022-07-09 22:55
ERRATUM:

My remark about CORS is valid in general but does not apply in this case:  
The seaborn penguins.csv file is hosted under `https://raw.githubusercontent.com` which allows all origins.  

You can get it as follows:

```py
# cell
# penguins = sns.load_dataset("penguins")
# fails as it uses urllib not available in pyodide

# cell
url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv'

# cell
from pyodide.http import pyfetch

async def download(url, path):
    resp = await pyfetch(url)
    if resp.ok:
        with open(path, "wb") as f:
            f.write(await resp.bytes())
            print(f'saved {path}')
    else:
        print('download error')

# cell
await download(url, '/drive/test-seaborn/penguins.csv')

```

**Comment by oscar6echo** [comment] 2022-07-26 13:24
Or simpler:
```py
df = pandas.read_csv(pyodide.open_url(url))
```

Probably the issue can be closed ?

**Comment by jtpio** [comment] 2022-07-27 07:24
Thanks @oscar6echo, closing as answered.

@Karan-raj-dev feel free to re-open or create a new issue if needed, thanks!

**Closed by jtpio** 2022-07-27 07:24 UTC
Labels: bug

**Comment by SoumyadeepOSD** [comment] 2022-12-05 11:13
Yes I got the same issue.. 
![autoscr](https://user-images.githubusercontent.com/115442240/205623618-316142a7-a2a0-49ac-8e28-59144dc3c71c.png)
but why I don't know.

can anyone help me out what is the cause of this type of problem with some packages?
